artifact_location: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao06-AutoLog/meuMlflow/714645697110589396
creation_time: 1733071031613
experiment_id: '714645697110589396'
last_update_time: 1733071031613
lifecycle_stage: active
name: SGDregressor
