artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/809455941807007367/8fdb5ecf42f34ea99866bbe8c0b6fd03/artifacts
deleted_time: 1733001861188
end_time: 1732998128725
entry_point_name: ''
experiment_id: '809455941807007367'
lifecycle_stage: deleted
run_id: 8fdb5ecf42f34ea99866bbe8c0b6fd03
run_name: clean-zebra-645
run_uuid: 8fdb5ecf42f34ea99866bbe8c0b6fd03
source_name: ''
source_type: 4
source_version: ''
start_time: 1732998127980
status: 4
tags: []
user_id: mateu
