artifact_uri: file:///C:/Users/mateu/Documents/Norton/Projetos%20GIT/MLFlow-Curso-Udemy/examples/ex1/mytracks/316808488967761096/6aa8880d9ce14405a230f3a4f4453fdf/artifacts
end_time: 1756859571963
entry_point_name: ''
experiment_id: '316808488967761096'
lifecycle_stage: active
run_id: 6aa8880d9ce14405a230f3a4f4453fdf
run_name: glamorous-eel-643
source_name: ''
source_type: 4
source_version: ''
start_time: 1756859552714
status: 3
tags: []
user_id: mateu
