artifact_location: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/meuMlflow/459378365503234085
creation_time: 1733068984580
experiment_id: '459378365503234085'
last_update_time: 1733068984580
lifecycle_stage: active
name: SGDregressor
