digest: ce8bc647
name: dataset
profile: '{"num_rows": 399, "num_elements": 4788}'
schema: '{"mlflow_colspec": [{"type": "long", "name": "Unnamed: 0", "required": true},
  {"type": "double", "name": "fixed acidity", "required": true}, {"type": "double",
  "name": "volatile acidity", "required": true}, {"type": "double", "name": "citric
  acid", "required": true}, {"type": "double", "name": "residual sugar", "required":
  true}, {"type": "double", "name": "chlorides", "required": true}, {"type": "double",
  "name": "free sulfur dioxide", "required": true}, {"type": "double", "name": "total
  sulfur dioxide", "required": true}, {"type": "double", "name": "density", "required":
  true}, {"type": "double", "name": "pH", "required": true}, {"type": "double", "name":
  "sulphates", "required": true}, {"type": "double", "name": "alcohol", "required":
  true}]}'
source: '{"tags": {"mlflow.user": "mateu", "mlflow.source.name": "autolog.py", "mlflow.source.type":
  "LOCAL", "mlflow.source.git.commit": "a2ef3af63cdf3567f1cdfe2318067fb41ecf24a2"}}'
source_type: code
