artifact_location: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao07-Tracking
  Server/mytracks/0
creation_time: 1756861459709
experiment_id: '0'
last_update_time: 1756861459709
lifecycle_stage: active
name: Default
