artifact_location: file:///C:/Users/mateu/Documents/Norton/Projetos%20GIT/MLFlow-Curso-Udemy/examples/ex1/mytracks/0
creation_time: 1756859514631
experiment_id: '0'
last_update_time: 1756859514631
lifecycle_stage: active
name: Default
