artifact_location: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao06-AutoLog/meuMlflow/0
creation_time: 1733071031594
experiment_id: '0'
last_update_time: 1733071031594
lifecycle_stage: active
name: Default
