artifact_location: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao10-Evaluate/mytracks/0
creation_time: 1757004260157
experiment_id: '0'
last_update_time: 1757004260157
lifecycle_stage: active
name: Default
