artifact_location: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/0
creation_time: 1732987070386
experiment_id: '0'
last_update_time: 1732987070386
lifecycle_stage: active
name: Default
