artifact_location: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/146854822795567061
creation_time: 1732988655663
experiment_id: '146854822795567061'
last_update_time: 1732988655663
lifecycle_stage: active
name: Elastic_
