artifact_location: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao10-Evaluate/mytracks/693117567434068160
creation_time: 1757004260173
experiment_id: '693117567434068160'
last_update_time: 1757004260173
lifecycle_stage: active
name: LogisticRegression
