artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/809455941807007367/8fda1b1a1f1c42aeb8835b71193f143d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '809455941807007367'
lifecycle_stage: active
run_id: 8fda1b1a1f1c42aeb8835b71193f143d
run_name: serious-panda-730
run_uuid: 8fda1b1a1f1c42aeb8835b71193f143d
source_name: ''
source_type: 4
source_version: ''
start_time: 1733066638860
status: 1
tags: []
user_id: mateu
