artifact_uri: file:///C:/Users/mateu/Documents/Norton/Projetos%20GIT/MLFlow-Curso-Udemy/examples/ex1/mytracks/316808488967761096/5b6c679144fa48fdb63f73f179b39caa/artifacts
end_time: 1756859532282
entry_point_name: ''
experiment_id: '316808488967761096'
lifecycle_stage: active
run_id: 5b6c679144fa48fdb63f73f179b39caa
run_name: inquisitive-cat-158
source_name: ''
source_type: 4
source_version: ''
start_time: 1756859516313
status: 3
tags: []
user_id: mateu
