artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/364255944873683429/24557bafcacb4614a0b01a0796ba73bf/artifacts
end_time: 1732987076390
entry_point_name: ''
experiment_id: '364255944873683429'
lifecycle_stage: active
run_id: 24557bafcacb4614a0b01a0796ba73bf
run_name: likeable-fish-916
run_uuid: 24557bafcacb4614a0b01a0796ba73bf
source_name: ''
source_type: 4
source_version: ''
start_time: 1732987071147
status: 3
tags: []
user_id: mateu
