artifact_location: file:///C:/Users/mateu/Documents/Norton/Projetos%20GIT/MLFlow-Curso-Udemy/examples/ex1/mytracks/316808488967761096
creation_time: 1756859514661
experiment_id: '316808488967761096'
last_update_time: 1756859514661
lifecycle_stage: active
name: GradientBoss
