artifact_location: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao08-Model
  Components/mytracks/0
creation_time: 1756995626757
experiment_id: '0'
last_update_time: 1756995626757
lifecycle_stage: active
name: Default
