artifact_uri: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao07-Tracking
  Server/mytracks/296020691507486032/c27d60910dfd4046930ed7abb584a62f/artifacts
end_time: 1756910265482
entry_point_name: ''
experiment_id: '296020691507486032'
lifecycle_stage: active
run_id: c27d60910dfd4046930ed7abb584a62f
run_name: grandiose-fawn-79
source_name: ''
source_type: 4
source_version: ''
start_time: 1756910220517
status: 3
tags: []
user_id: mateu
