artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/meuMlflow/459378365503234085/abb7a37e76d24498bb42983fdc6ebf37/artifacts
end_time: 1733071488283
entry_point_name: ''
experiment_id: '459378365503234085'
lifecycle_stage: active
run_id: abb7a37e76d24498bb42983fdc6ebf37
run_name: exultant-auk-677
run_uuid: abb7a37e76d24498bb42983fdc6ebf37
source_name: ''
source_type: 4
source_version: ''
start_time: 1733071481368
status: 3
tags: []
user_id: mateu
