artifact_uri: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao08-Model
  Components/mytracks/928576216928126223/9d0f70799665455b8d81e1a64ac152f8/artifacts
end_time: 1756995633533
entry_point_name: ''
experiment_id: '928576216928126223'
lifecycle_stage: active
run_id: 9d0f70799665455b8d81e1a64ac152f8
run_name: wistful-squid-684
source_name: ''
source_type: 4
source_version: ''
start_time: 1756995627668
status: 3
tags: []
user_id: mateu
