artifact_location: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao08-Model
  Components/mytracks/928576216928126223
creation_time: 1756995626768
experiment_id: '928576216928126223'
last_update_time: 1756995626768
lifecycle_stage: active
name: LogisticRegression
