artifact_location: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/364255944873683429
creation_time: 1732987070414
experiment_id: '364255944873683429'
last_update_time: 1732987070414
lifecycle_stage: active
name: ExperimentRegElastic
