artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/364255944873683429/f20efd1c31de4d4688141892e4abd6eb/artifacts
end_time: 1732987103250
entry_point_name: ''
experiment_id: '364255944873683429'
lifecycle_stage: active
run_id: f20efd1c31de4d4688141892e4abd6eb
run_name: glamorous-rook-986
run_uuid: f20efd1c31de4d4688141892e4abd6eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1732987098364
status: 3
tags: []
user_id: mateu
