artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/146854822795567061/fc9bac3bca1f4b26b864e190df953684/artifacts
end_time: 1732988662814
entry_point_name: ''
experiment_id: '146854822795567061'
lifecycle_stage: active
run_id: fc9bac3bca1f4b26b864e190df953684
run_name: selective-kite-720
run_uuid: fc9bac3bca1f4b26b864e190df953684
source_name: ''
source_type: 4
source_version: ''
start_time: 1732988656733
status: 3
tags: []
user_id: mateu
