artifact_uri: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao07-Tracking
  Server/mytracks/296020691507486032/677feb4409a64736adb63d2d46469fec/artifacts
end_time: 1756910976371
entry_point_name: ''
experiment_id: '296020691507486032'
lifecycle_stage: active
run_id: 677feb4409a64736adb63d2d46469fec
run_name: rogue-squid-790
source_name: ''
source_type: 4
source_version: ''
start_time: 1756910864206
status: 3
tags: []
user_id: mateu
