artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao06-AutoLog/meuMlflow/714645697110589396/ddda3a7a5b0e4d8f8a76d267e7a0e956/artifacts
end_time: 1756857880549
entry_point_name: ''
experiment_id: '714645697110589396'
lifecycle_stage: active
run_id: ddda3a7a5b0e4d8f8a76d267e7a0e956
run_name: funny-panda-415
source_name: ''
source_type: 4
source_version: ''
start_time: 1756857863424
status: 3
tags: []
user_id: mateu
