artifact_uri: file:C:/Users/mateu/Documents/Norton/Projetos GIT/MLFlow-Curso-Udemy/Secao08-Model
  Components/mytracks/928576216928126223/7d31f24ecbde45fdaf417383200a95d8/artifacts
end_time: 1756995683289
entry_point_name: ''
experiment_id: '928576216928126223'
lifecycle_stage: active
run_id: 7d31f24ecbde45fdaf417383200a95d8
run_name: debonair-shad-69
source_name: ''
source_type: 4
source_version: ''
start_time: 1756995670183
status: 3
tags: []
user_id: mateu
