artifact_uri: file:///C:/Users/mateu/Documents/Norton/Projetos%20GIT/MLFlow-Curso-Udemy/examples/ex1/mytracks/316808488967761096/c0d08cfb715d4dd4bebfabb9cb647dbf/artifacts
end_time: 1756859613276
entry_point_name: ''
experiment_id: '316808488967761096'
lifecycle_stage: active
run_id: c0d08cfb715d4dd4bebfabb9cb647dbf
run_name: nosy-duck-279
source_name: ''
source_type: 4
source_version: ''
start_time: 1756859606655
status: 3
tags: []
user_id: mateu
