artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao06-AutoLog/meuMlflow/714645697110589396/e88cf114866d4744982d6bd2282d03dd/artifacts
end_time: 1756858500347
entry_point_name: ''
experiment_id: '714645697110589396'
lifecycle_stage: active
run_id: e88cf114866d4744982d6bd2282d03dd
run_name: fortunate-shrimp-596
source_name: ''
source_type: 4
source_version: ''
start_time: 1756858482657
status: 3
tags: []
user_id: mateu
