artifact_location: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/mytracks/809455941807007367
creation_time: 1732998126918
experiment_id: '809455941807007367'
last_update_time: 1732998126918
lifecycle_stage: active
name: GradientBoss
