artifact_uri: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao06-AutoLog/meuMlflow/714645697110589396/bbec3dd1437641d483b002f4269aa0e4/artifacts
end_time: 1756858374524
entry_point_name: ''
experiment_id: '714645697110589396'
lifecycle_stage: active
run_id: bbec3dd1437641d483b002f4269aa0e4
run_name: mysterious-rat-425
source_name: ''
source_type: 4
source_version: ''
start_time: 1756858371262
status: 4
tags: []
user_id: mateu
