artifact_location: file:C:/Users/mateu/Documents/MEGA/Projetos-git/MLFlow-Curso-Udemy/Secao04-Tracking/meuMlflow/0
creation_time: 1733068984545
experiment_id: '0'
last_update_time: 1733068984545
lifecycle_stage: active
name: Default
